---
title: Jake Atkin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
name: Jake Atkin
email: jake@jakeatkin.co.uk
tagline: Digital, UX, Service and Product Design
description: 'Jake Atkin is a Lancaster-based multidisciplinary designer with a penchant
  for digital design, UX and branding. I design and create beautiful brands and products.

'
baseurl: 
url: https://jakeatkin.co.uk
twitter_username: theatkinator
excerpt_separator: "<!--more-->"
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
future: true
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:title/"
